inherited frmStocksCalc: TfrmStocksCalc
  Left = 387
  Top = 370
  Caption = 'frmStocksCalc'
  ClientHeight = 190
  ClientWidth = 359
  OldCreateOrder = True
  PixelsPerInch = 96
  TextHeight = 15
  inherited pnlAddressBar: TPanel
    Width = 359
    inherited RzFormShape1: TRzFormShape
      Width = 359
    end
    inherited Image1: TImage
      Left = 149
    end
    object lblInfo: TRzLabel [4]
      Left = 23
      Top = 32
      Width = 313
      Height = 15
      Alignment = taCenter
      AutoSize = False
      Caption = #35831#28857#20987#24320#22987#35745#31639
      Transparent = True
      ShadowColor = clWhite
      ShadowDepth = 1
      TextStyle = tsShadow
    end
    object RzLabel1: TRzLabel [5]
      Left = 10
      Top = 7
      Width = 61
      Height = 16
      Alignment = taCenter
      Caption = #21488#36134#35745#31639
      Transparent = True
      Layout = tlCenter
      ShadowColor = 16250871
      ShadowDepth = 1
      TextStyle = tsShadow
    end
    inherited RzBmpButton2: TRzBmpButton
      Left = 334
    end
  end
  inherited RzPanel1: TRzPanel
    Width = 359
    Height = 160
    object RzProgressBar1: TRzProgressBar
      Left = 45
      Top = 49
      Width = 273
      BorderInner = fsFlat
      BorderOuter = fsFlatRounded
      BorderWidth = 0
      InteriorOffset = 0
      PartsComplete = 0
      Percent = 0
      TotalParts = 0
    end
    object RzBorder1: TRzBorder
      Left = 3
      Top = 96
      Width = 353
      Height = 2
    end
    object RzLabel2: TRzLabel
      Left = 1
      Top = 1
      Width = 357
      Height = 16
      Align = alTop
      Alignment = taCenter
      Caption = #38144#21806#26085#26399
      Transparent = True
      Layout = tlCenter
      ShadowColor = 16250871
      ShadowDepth = 1
      TextStyle = tsShadow
    end
    object btnCalc: TRzBmpButton
      Left = 133
      Top = 110
      Width = 106
      Height = 29
      Bitmaps.TransparentColor = clFuchsia
      Bitmaps.Up.Data = {
        76240000424D762400000000000036000000280000006A0000001D0000000100
        1800000000004024000000000000000000000000000000000000EBEBEBEAEAEA
        E5E5E5D9D9D9D0D0D0CECECECDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCECECED0D0D0D9D9D9E5E5E5EAEAEAEBEBEB0000E9E9E9E0E0E0
        C7C7C7AAAAAA9999999393939292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        929292929292939393999999AAAAAAC7C7C7E0E0E0E9E9E90000E4E4E4C7C7C7
        C6C6C6D2D2D2DADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADAD0D0D0B9B9B98A8A8A9C9C9CC5C5C5E4E4E40000DADADAD8D8D8
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADAD3D3D38E8E8EA9A9A9D9D9D90000E1E1E1DFDFDF
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADABBBBBB979797D0D0D00000EAEAEADBDBDB
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADAD5D5D5929292CECECE0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA929292CECECE0000EEEEEEDBDBDB
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADA979797D0D0D00000EFEFEFDFDFDF
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADAD6D6D6A9A9A9D9D9D90000EDEDEDE9E9E9
        DBDBDBDADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADAC6C6C6C5C5C5E4E4E40000EBEBEBEFEFEF
        E8E8E8E0E0E0DCDCDCDADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADAD7D7D7CACACAE0E0E0E9E9E90000EBEBEBEBEBEB
        EAEAEAE6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
        E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
        E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
        E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
        E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
        E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
        E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
        E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
        E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
        E6E6E6E5E5E5E1E1E1DADADAD9D9D9E5E5E5EAEAEAEBEBEB0000}
      Color = clBtnFace
      Anchors = [akTop, akRight]
      Caption = #24320#22987#35745#31639
      TabOrder = 0
      OnClick = btnCalcClick
    end
  end
  object Timer1: TTimer
    Left = 64
    Top = 142
  end
end
