inherited frmSelectGoods: TfrmSelectGoods
  Left = 319
  Top = 148
  Caption = #21830#21697#36873#25321#26694
  ClientHeight = 425
  ClientWidth = 605
  OldCreateOrder = True
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 15
  inherited RzPanel1: TRzPanel
    Width = 605
    Height = 397
    object RzPanel2: TRzPanel
      Left = 1
      Top = 1
      Width = 603
      Height = 354
      Align = alClient
      BorderOuter = fsNone
      BorderColor = 15461355
      BorderWidth = 5
      Color = 15461355
      TabOrder = 0
      object Splitter1: TSplitter
        Left = 145
        Top = 5
        Height = 344
      end
      object RzPanel3: TRzPanel
        Left = 5
        Top = 5
        Width = 140
        Height = 344
        Align = alLeft
        BorderOuter = fsFlatRounded
        TabOrder = 0
        object rzTree: TRzTreeView
          Left = 2
          Top = 2
          Width = 136
          Height = 340
          SelectionPen.Color = clBtnShadow
          Align = alClient
          Ctl3D = True
          FrameVisible = True
          Indent = 19
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 0
          OnChange = rzTreeChange
        end
      end
      object RzPanel5: TRzPanel
        Left = 148
        Top = 5
        Width = 450
        Height = 344
        Align = alClient
        BorderOuter = fsFlatRounded
        Color = 15461355
        TabOrder = 1
        object DBGridEh1: TDBGridEh
          Left = 2
          Top = 44
          Width = 446
          Height = 298
          Align = alClient
          AllowedOperations = [alopUpdateEh]
          AutoFitColWidths = True
          DataSource = DataSource1
          Flat = True
          FooterColor = clWindow
          FooterFont.Charset = GB2312_CHARSET
          FooterFont.Color = clBlack
          FooterFont.Height = -15
          FooterFont.Name = #23435#20307
          FooterFont.Style = []
          FrozenCols = 1
          ImeName = #20013#25991'('#31616#20307') - '#25628#29399#20116#31508#36755#20837#27861
          Options = [dgTitles, dgColumnResize, dgColLines, dgRowLines, dgTabs, dgRowSelect, dgAlwaysShowSelection, dgConfirmDelete, dgCancelOnExit]
          OptionsEh = [dghFixed3D, dghHighlightFocus, dghClearSelection]
          RowHeight = 23
          TabOrder = 0
          TitleFont.Charset = GB2312_CHARSET
          TitleFont.Color = clBlack
          TitleFont.Height = -15
          TitleFont.Name = #23435#20307
          TitleFont.Style = []
          UseMultiTitle = True
          IsDrawNullRow = False
          CurrencySymbol = #65509
          DecimalNumber = 2
          DigitalNumber = 12
          OnDblClick = DBGridEh1DblClick
          OnDrawColumnCell = DBGridEh1DrawColumnCell
          OnKeyDown = DBGridEh1KeyDown
          Columns = <
            item
              EditButtons = <>
              FieldName = 'GODS_CODE'
              Footer.Value = #35760#24405#25968#65306
              Footer.ValueType = fvtStaticText
              Footers = <>
              ReadOnly = True
              Title.Caption = #36135#21495
              Title.Color = clWhite
              Width = 76
            end
            item
              EditButtons = <>
              FieldName = 'GODS_NAME'
              Footer.ValueType = fvtCount
              Footers = <>
              ReadOnly = True
              Title.Caption = #21830#21697#21517#31216
              Title.Color = clWhite
              Width = 119
            end
            item
              EditButtons = <>
              FieldName = 'BARCODE'
              Footers = <>
              Title.Caption = #26465#30721
              Title.Color = clWhite
              Width = 123
            end
            item
              EditButtons = <>
              FieldName = 'AMOUNT'
              Footers = <>
              ReadOnly = True
              Title.Caption = #24211#23384#37327
              Title.Color = clWhite
              Width = 51
            end
            item
              EditButtons = <>
              FieldName = 'UNIT_ID'
              Footers = <>
              ReadOnly = True
              Title.Caption = #21333#20301
              Title.Color = clWhite
              Width = 25
            end
            item
              EditButtons = <>
              FieldName = 'NEW_OUTPRICE'
              Footers = <>
              Title.Caption = #26631#20934#21806#20215
              Title.Color = clWhite
              Width = 43
            end>
        end
        object fndPanel: TPanel
          Left = 2
          Top = 2
          Width = 446
          Height = 42
          Align = alTop
          BevelOuter = bvLowered
          Color = 15461355
          TabOrder = 1
          object RzPanel6: TRzPanel
            Left = 1
            Top = 1
            Width = 444
            Height = 40
            Align = alClient
            BorderOuter = fsNone
            BorderWidth = 1
            Color = 14606046
            TabOrder = 0
            object search: TRzPanel
              Left = 27
              Top = 5
              Width = 250
              Height = 29
              BorderOuter = fsNone
              TabOrder = 0
              DesignSize = (
                250
                29)
              object barcode_input_left: TImage
                Left = 0
                Top = 0
                Width = 6
                Height = 29
                Align = alLeft
                AutoSize = True
                Picture.Data = {
                  07544269746D61707A020000424D7A0200000000000036000000280000000600
                  00001D000000010018000000000044020000C30E0000C30E0000000000000000
                  0000DEDEDEDEDEDEDEDEDEE6E6E6F5F5F5FCFCFC0000DEDEDEDEDEDEE1E1E1E9
                  E9E9F4F4F4FBFBFB0000DEDEDECBCBCBE0E0E0FAFAFAFFFFFFFFFFFF0000CBCB
                  CBCACACAF4F4F4FFFFFFFFFFFFFFFFFF0000ABABABD9D9D9FCFCFCFFFFFFFFFF
                  FFFFFFFF0000A1A1A1DDDDDDFEFEFEFFFFFFFFFFFFFFFFFF00009E9E9EDEDEDE
                  FFFFFFFFFFFFFFFFFFFFFFFF00009E9E9EDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF
                  00009E9E9EDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF00009E9E9EDEDEDEFFFFFFFF
                  FFFFFFFFFFFFFFFF00009E9E9EDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF00009E9E
                  9EDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF00009E9E9EDEDEDEFFFFFFFFFFFFFFFF
                  FFFFFFFF00009E9E9EDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF00009E9E9EDEDEDE
                  FFFFFFFFFFFFFFFFFFFFFFFF00009E9E9EDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF
                  00009E9E9EDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF00009E9E9EDEDEDEFFFFFFFF
                  FFFFFFFFFFFFFFFF00009E9E9EDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF00009E9E
                  9EDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF00009E9E9EDEDEDEFFFFFFFFFFFFFFFF
                  FFFFFFFF00009E9E9EDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF00009D9D9DDDDDDD
                  FEFEFEFFFFFFFFFFFFFFFFFF00009B9B9BD9D9D9FCFCFCFFFFFFFFFFFFFFFFFF
                  0000979797C9C9C9F4F4F4FFFFFFFFFFFFFFFFFF00009B9B9BADADADE0E0E0FA
                  FAFAFFFFFFFFFFFF0000DEDEDE929292B9B9B9DFDFDFF3F3F3FBFBFB0000DEDE
                  DEDEDEDE919191ACACACC6C6C6D6D6D60000DEDEDEDEDEDEDEDEDEA2A2A29999
                  999999990000}
              end
              object barcode_input_right: TImage
                Left = 245
                Top = 0
                Width = 5
                Height = 29
                Align = alRight
                AutoSize = True
                Picture.Data = {
                  07544269746D617006020000424D060200000000000036000000280000000500
                  00001D0000000100180000000000D0010000120B0000120B0000000000000000
                  0000FCFCFCF5F5F5DEDEDEDEDEDEDEDEDE00FCFCFCFCFCFCFFFFFFDEDEDEDEDE
                  DE00FFFFFFFFFFFFFDFDFDFFFFFFDEDEDE00FFFFFFFFFFFFFFFFFFFCFCFCF7F7
                  F700FFFFFFFFFFFFFFFFFFFDFDFDFDFDFD00FFFFFFFFFFFFFFFFFFFEFEFEFFFF
                  FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  FF00FFFFFFFFFFFFFFFFFFFEFEFEFFFFFF00FFFFFFFFFFFFFFFFFFFCFCFCFDFD
                  FD00FFFFFFFFFFFFFFFFFFF5F5F5F7F7F700FFFFFFFFFFFFFAFAFAE7E7E7E6E6
                  E600FBFBFBF3F3F3DFDFDFE2E2E2DEDEDE00D6D6D6C6C6C6CBCBCBDEDEDEDEDE
                  DE00AEAEAECBCBCBDEDEDEDEDEDEDEDEDE00}
              end
              object search_input_line: TImage
                Left = 6
                Top = 0
                Width = 239
                Height = 29
                Hint = #25195#30721#25353' pause '#20581
                Align = alClient
                AutoSize = True
                Picture.Data = {
                  07544269746D61707A020000424D7A0200000000000036000000280000000600
                  00001D0000000100180000000000440200000000000000000000000000000000
                  0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
                  FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
                  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
                  FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
                  FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
                  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
                  FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
                  FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
                  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
                  FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                  0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
                  FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000DEDE
                  DEDEDEDEDEDEDEDEDEDEDEDEDEDEDEDE00009E9E9E9E9E9E9E9E9E9E9E9E9E9E
                  9E9E9E9E0000}
                Stretch = True
              end
              object edtSearch: TEdit
                Tag = -1
                Left = 5
                Top = 7
                Width = 240
                Height = 18
                Hint = #36755#20837#21830#21697#21517#31216#12289#36135#21495#12289#26465#30721
                Anchors = [akLeft, akTop, akRight]
                BevelInner = bvNone
                BevelOuter = bvNone
                BorderStyle = bsNone
                TabOrder = 0
                Text = #36755#20837#21830#21697#21517#31216#12289#36135#21495#12289#26465#30721
                OnChange = edtSearchChange
                OnEnter = edtSearchEnter
                OnExit = edtSearchExit
                OnKeyPress = edtSearchKeyPress
              end
            end
            object btnSearch: TRzBmpButton
              Left = 302
              Top = 5
              Width = 72
              Bitmaps.TransparentColor = clFuchsia
              Bitmaps.Up.Data = {
                86190000424D86190000000000003600000028000000480000001E0000000100
                1800000000005019000000000000000000000000000000000000DEDEDEDEDEDE
                DDDDDDDADADAD1D1D1C8C8C8C3C3C3C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1
                C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1
                C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1
                C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1
                C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1
                C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C1C2C2C2
                C5C5C5CCCCCCD5D5D5DCDCDCDEDEDEDEDEDEDEDEDEDDDDDDD5D5D5C2C2C2A9A9
                A99696968C8C8C8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A
                8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A
                8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A
                8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A
                8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A
                8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A8A9090909E9E9EB5B5
                B5CDCDCDDBDBDBDEDEDEDEDEDED6D6D6BCBCBCB8B8B8C8C8C8DADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADAD0D0D0BABABA8F8F8F898989AAAAAACDCDCDDC
                DCDCDCDCDCCACACAD0D0D0DADADADADADADBDBDBDADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADAA2A2A2898989B4B4B4D5D5D5D7D7D7DBDBDB
                DCDCDCDADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADAD9D9D98E8E8E9C9C9CCBCBCBD8D8D8E7E7E7DBDBDBDADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DAC0C0C08E8E8EC4C4C4DEDEDEE7E7E7DADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADAD5D5D58A8A8AC2
                C2C2DFDFDFE7E7E7DADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADA8A8A8AC1C1C1DFDFDFE6E6E6
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADA8A8A8AC1C1C1DFDFDFE6E6E6DADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADA8A8A8AC1C1C1DFDFDFE6E6E6DADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADA8A8A8AC1
                C1C1DFDFDFE6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADA8A8A8AC1C1C1DFDFDFE6E6E6
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADA8A8A8AC1C1C1DFDFDFE6E6E6DADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADA8A8A8AC1C1C1DFDFDFE6E6E6DADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADA8A8A8AC1
                C1C1DFDFDFE6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADA8A8A8AC1C1C1DFDFDFE6E6E6
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADA8A8A8AC1C1C1DFDFDFE6E6E6DADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADA8A8A8AC1C1C1DFDFDFE6E6E6DADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADA8A8A8AC1
                C1C1DFDFDFE6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADA8A8A8AC1C1C1DFDFDFE6E6E6
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADA8A8A8AC1C1C1DFDFDFE6E6E6DADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADA8A8A8AC1C1C1DFDFDFE6E6E6DADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADA8A8A8AC1
                C1C1DFDFDFE6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADA8B8B8BC3C3C3E1E1E1E8E8E8
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADAD9D9D9939393C6C6C6E2E2E2ECECECDBDBDBDADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DACECECEA7A7A7D0D0D0DFDFDFEFEFEFE3E3E3DADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADABABABAC1C1C1DA
                DADADEDEDEE4E4E4EEEEEEE3E3E3DBDBDBDADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
                DADADADADADADADADADADADADADAD2D2D2BEBEBED6D6D6DDDDDDDEDEDEDEDEDE
                E3E3E3EBEBEBE7E7E7E4E4E4E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
                E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
                E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
                E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
                E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
                E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E1E1E1
                DEDEDED1D1D1CBCBCBD7D7D7DDDDDDDEDEDEDEDEDEDEDEDEDEDEDEDEDEDEDFDF
                DFDCDCDCDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDB
                DBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDB
                DBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDB
                DBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDB
                DBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDB
                DBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDADADAD6D6D6D9D9D9DCDC
                DCDEDEDEDEDEDEDEDEDE}
              Color = clBtnFace
              Caption = #25628#32034
              TabOrder = 1
              OnClick = btnSearchClick
            end
          end
        end
      end
    end
    object RzPanel4: TRzPanel
      Left = 1
      Top = 355
      Width = 603
      Height = 41
      Align = alBottom
      BorderOuter = fsNone
      BorderColor = 15461355
      Color = 15461355
      TabOrder = 1
      object btnOk: TRzBmpButton
        Left = 411
        Top = 3
        Width = 72
        Bitmaps.TransparentColor = clFuchsia
        Bitmaps.Up.Data = {
          86190000424D86190000000000003600000028000000480000001E0000000100
          1800000000005019000000000000000000000000000000000000EBEBEBEBEBEB
          EAEAEAE6E6E6DDDDDDD4D4D4CECECECDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
          CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
          CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
          CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
          CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
          CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCECECE
          D0D0D0D8D8D8E2E2E2E9E9E9EBEBEBEBEBEBEBEBEBEAEAEAE2E2E2CECECEB3B3
          B39F9F9F94949492929292929292929292929292929292929292929292929292
          9292929292929292929292929292929292929292929292929292929292929292
          9292929292929292929292929292929292929292929292929292929292929292
          9292929292929292929292929292929292929292929292929292929292929292
          9292929292929292929292929292929292929292929292929292929292929292
          929292929292929292929292929292929292929292939393989898A7A7A7C0C0
          C0D9D9D9E7E7E7EBEBEBEBEBEBE3E3E3C7C7C7BCBCBCC9C9C9DADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADAD0D0D0BCBCBC959595919191B4B4B4D9D9D9E9
          E9E9E9E9E9D4D4D4D2D2D2DADADADADADADBDBDBDADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADAA6A6A6919191BFBFBFE2E2E2E4E4E4DDDDDD
          DCDCDCDADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADAD9D9D9939393A5A5A5D7D7D7E2E2E2E7E7E7DBDBDBDADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DAC1C1C1969696CFCFCFE4E4E4E7E7E7DADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADAD5D5D5929292CE
          CECEE5E5E5E7E7E7DADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
          CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
          CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
          CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
          CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADA939393CECECEE8E8E8E8E8E8
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADAD9D9D99C9C9CD2D2D2EAEAEAECECECDBDBDBDADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DACFCFCFB1B1B1DCDCDCEBEBEBF0F0F0E3E3E3DADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADABFBFBFCDCDCDE6
          E6E6EBEBEBECECECEEEEEEE3E3E3DBDBDBDADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADAD3D3D3C9C9C9E3E3E3EAEAEAEBEBEBEBEBEB
          EBEBEBEBEBEBE7E7E7E4E4E4E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E1E1E1
          DEDEDED4D4D4D6D6D6E4E4E4EAEAEAEBEBEBEBEBEBEBEBEBEBEBEBEAEAEAE7E7
          E7E4E4E4E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E1E1E1E1E1E1E5E5E5E9E9
          E9EBEBEBEBEBEBEBEBEB}
        Color = clBtnFace
        Caption = #30830#23450
        TabOrder = 0
        OnClick = btnOkClick
      end
      object btnCancel: TRzBmpButton
        Left = 507
        Top = 3
        Width = 72
        Bitmaps.TransparentColor = clFuchsia
        Bitmaps.Up.Data = {
          86190000424D86190000000000003600000028000000480000001E0000000100
          1800000000005019000000000000000000000000000000000000EBEBEBEBEBEB
          EAEAEAE6E6E6DDDDDDD4D4D4CECECECDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
          CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
          CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
          CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
          CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
          CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCECECE
          D0D0D0D8D8D8E2E2E2E9E9E9EBEBEBEBEBEBEBEBEBEAEAEAE2E2E2CECECEB3B3
          B39F9F9F94949492929292929292929292929292929292929292929292929292
          9292929292929292929292929292929292929292929292929292929292929292
          9292929292929292929292929292929292929292929292929292929292929292
          9292929292929292929292929292929292929292929292929292929292929292
          9292929292929292929292929292929292929292929292929292929292929292
          929292929292929292929292929292929292929292939393989898A7A7A7C0C0
          C0D9D9D9E7E7E7EBEBEBEBEBEBE3E3E3C7C7C7BCBCBCC9C9C9DADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADAD0D0D0BCBCBC959595919191B4B4B4D9D9D9E9
          E9E9E9E9E9D4D4D4D2D2D2DADADADADADADBDBDBDADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADAA6A6A6919191BFBFBFE2E2E2E4E4E4DDDDDD
          DCDCDCDADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADAD9D9D9939393A5A5A5D7D7D7E2E2E2E7E7E7DBDBDBDADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DAC1C1C1969696CFCFCFE4E4E4E7E7E7DADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADAD5D5D5929292CE
          CECEE5E5E5E7E7E7DADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
          CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
          CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
          CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
          CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADA939393CECECEE8E8E8E8E8E8
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADAD9D9D99C9C9CD2D2D2EAEAEAECECECDBDBDBDADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DACFCFCFB1B1B1DCDCDCEBEBEBF0F0F0E3E3E3DADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADABFBFBFCDCDCDE6
          E6E6EBEBEBECECECEEEEEEE3E3E3DBDBDBDADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
          DADADADADADADADADADADADADADAD3D3D3C9C9C9E3E3E3EAEAEAEBEBEBEBEBEB
          EBEBEBEBEBEBE7E7E7E4E4E4E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E1E1E1
          DEDEDED4D4D4D6D6D6E4E4E4EAEAEAEBEBEBEBEBEBEBEBEBEBEBEBEAEAEAE7E7
          E7E4E4E4E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
          E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E1E1E1E1E1E1E5E5E5E9E9
          E9EBEBEBEBEBEBEBEBEB}
        Color = clBtnFace
        Caption = #21462#28040
        TabOrder = 1
        OnClick = btnCancelClick
      end
    end
  end
  inherited pnlAddressBar: TPanel
    Width = 605
    inherited Image3: TImage
      Width = 597
    end
    inherited RzLabel1: TRzLabel
      Width = 7
      Caption = ''
    end
    inherited Image1: TImage
      Left = 601
    end
    object RzLabel26: TRzLabel [5]
      Left = 10
      Top = 7
      Width = 76
      Height = 16
      Alignment = taCenter
      Caption = #21830#21697#36873#25321#26694
      Transparent = True
      Layout = tlCenter
      ShadowColor = 16250871
      ShadowDepth = 1
      TextStyle = tsShadow
    end
    inherited btnClose: TRzBmpButton
      Left = 576
    end
    inherited RzBmpButton4: TRzBmpButton
      Left = 524
      Visible = False
    end
    inherited btnWindow: TRzBmpButton
      Left = 550
      Visible = False
    end
  end
  object cdsList: TZQuery
    FieldDefs = <>
    CachedUpdates = True
    Params = <>
    Left = 342
    Top = 250
  end
  object DataSource1: TDataSource
    DataSet = cdsList
    Left = 302
    Top = 250
  end
end
