object frmDropForm: TfrmDropForm
  Left = 423
  Top = 297
  BorderStyle = bsNone
  Caption = 'frmDropForm'
  ClientHeight = 263
  ClientWidth = 263
  Color = clBtnFace
  Font.Charset = GB2312_CHARSET
  Font.Color = clWindowText
  Font.Height = -15
  Font.Name = #23435#20307
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  OnDeactivate = FormDeactivate
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 15
  object RzPanel1: TRzPanel
    Left = 0
    Top = 0
    Width = 263
    Height = 263
    Align = alClient
    BorderOuter = fsFlat
    Color = clWhite
    TabOrder = 0
  end
end
