inherited frmGoodsSort: TfrmGoodsSort
  Left = 521
  Top = 272
  Caption = #21830#21697#20998#31867
  ClientHeight = 185
  ClientWidth = 339
  OldCreateOrder = True
  PixelsPerInch = 96
  TextHeight = 15
  inherited pnlAddressBar: TPanel
    Width = 339
    TabOrder = 2
    inherited RzFormShape1: TRzFormShape
      Width = 339
    end
    inherited Image1: TImage
      Left = 129
    end
    object Label1: TLabel [4]
      Left = 17
      Top = 30
      Width = 96
      Height = 15
      Caption = #28155#21152#21830#21697#20998#31867
      Font.Charset = GB2312_CHARSET
      Font.Color = clBlack
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = [fsBold]
      ParentFont = False
    end
    object RzLabel26: TRzLabel [5]
      Left = 10
      Top = 7
      Width = 61
      Height = 16
      Alignment = taCenter
      Caption = #21830#21697#20998#31867
      Transparent = True
      Layout = tlCenter
      ShadowColor = 16250871
      ShadowDepth = 1
      TextStyle = tsShadow
    end
    inherited RzBmpButton2: TRzBmpButton
      Left = 314
    end
  end
  inherited RzPanel1: TRzPanel
    Width = 339
    Height = 155
    object RzPanel45: TRzPanel
      Left = 38
      Top = 14
      Width = 260
      Height = 31
      BorderOuter = fsStatus
      BorderWidth = 1
      Color = clWhite
      FlatColor = 9145227
      TabOrder = 0
      DesignSize = (
        260
        31)
      object RzPanel46: TRzPanel
        Left = 2
        Top = 2
        Width = 103
        Height = 27
        Align = alLeft
        BorderOuter = fsFlat
        BorderSides = [sdRight, sdBottom]
        FlatColor = clGray
        TabOrder = 0
        object RzBackground7: TRzBackground
          Left = 0
          Top = 0
          Width = 102
          Height = 26
          Active = True
          Align = alClient
          FrameColor = 9145227
          GradientColorStart = clWhite
          GradientColorStop = 14277081
          ImageStyle = isStretch
          ShowGradient = True
          ShowImage = False
          ShowTexture = False
        end
        object RzLabel15: TRzLabel
          Left = 0
          Top = 0
          Width = 102
          Height = 26
          Align = alClient
          Alignment = taCenter
          Caption = #19978#32423#20998#31867
          Font.Charset = GB2312_CHARSET
          Font.Color = clBlack
          Font.Height = -15
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = True
          Layout = tlCenter
          ShadowColor = 16250871
          ShadowDepth = 1
          TextStyle = tsShadow
        end
      end
      object edtSUP_SORT_ID: TcxButtonEdit
        Left = 105
        Top = 4
        Width = 153
        Height = 23
        Anchors = [akLeft, akTop, akRight]
        Properties.Buttons = <
          item
            Default = True
          end>
        Properties.ReadOnly = True
        Properties.OnButtonClick = edtSUP_SORT_IDPropertiesButtonClick
        Style.BorderStyle = ebsUltraFlat
        Style.Edges = [bLeft, bTop, bRight, bBottom]
        Style.ButtonStyle = btsUltraFlat
        Style.ButtonTransparency = ebtInactive
        TabOrder = 1
        OnKeyDown = edtSUP_SORT_IDKeyDown
        OnKeyPress = edtSUP_SORT_IDKeyPress
      end
    end
    object btnSave: TRzBmpButton
      Left = 75
      Top = 112
      Width = 72
      Bitmaps.TransparentColor = clFuchsia
      Bitmaps.Up.Data = {
        86190000424D86190000000000003600000028000000480000001E0000000100
        1800000000005019000000000000000000000000000000000000EBEBEBEBEBEB
        EAEAEAE6E6E6DDDDDDD4D4D4CECECECDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCECECE
        D0D0D0D8D8D8E2E2E2E9E9E9EBEBEBEBEBEBEBEBEBEAEAEAE2E2E2CECECEB3B3
        B39F9F9F94949492929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        929292929292929292929292929292929292929292939393989898A7A7A7C0C0
        C0D9D9D9E7E7E7EBEBEBEBEBEBE3E3E3C7C7C7BCBCBCC9C9C9DADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADAD0D0D0BCBCBC959595919191B4B4B4D9D9D9E9
        E9E9E9E9E9D4D4D4D2D2D2DADADADADADADBDBDBDADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADAA6A6A6919191BFBFBFE2E2E2E4E4E4DDDDDD
        DCDCDCDADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADAD9D9D9939393A5A5A5D7D7D7E2E2E2E7E7E7DBDBDBDADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DAC1C1C1969696CFCFCFE4E4E4E7E7E7DADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADAD5D5D5929292CE
        CECEE5E5E5E7E7E7DADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
        CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
        CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
        CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
        CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADA939393CECECEE8E8E8E8E8E8
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADAD9D9D99C9C9CD2D2D2EAEAEAECECECDBDBDBDADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DACFCFCFB1B1B1DCDCDCEBEBEBF0F0F0E3E3E3DADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADABFBFBFCDCDCDE6
        E6E6EBEBEBECECECEEEEEEE3E3E3DBDBDBDADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADAD3D3D3C9C9C9E3E3E3EAEAEAEBEBEBEBEBEB
        EBEBEBEBEBEBE7E7E7E4E4E4E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E1E1E1
        DEDEDED4D4D4D6D6D6E4E4E4EAEAEAEBEBEBEBEBEBEBEBEBEBEBEBEAEAEAE7E7
        E7E4E4E4E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E1E1E1E1E1E1E5E5E5E9E9
        E9EBEBEBEBEBEBEBEBEB}
      Color = clBtnFace
      Caption = #20445#23384
      TabOrder = 1
      OnClick = btnSaveClick
    end
    object btnClose: TRzBmpButton
      Left = 195
      Top = 112
      Width = 72
      Bitmaps.TransparentColor = clFuchsia
      Bitmaps.Up.Data = {
        86190000424D86190000000000003600000028000000480000001E0000000100
        1800000000005019000000000000000000000000000000000000EBEBEBEBEBEB
        EAEAEAE6E6E6DDDDDDD4D4D4CECECECDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
        CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCECECE
        D0D0D0D8D8D8E2E2E2E9E9E9EBEBEBEBEBEBEBEBEBEAEAEAE2E2E2CECECEB3B3
        B39F9F9F94949492929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        9292929292929292929292929292929292929292929292929292929292929292
        929292929292929292929292929292929292929292939393989898A7A7A7C0C0
        C0D9D9D9E7E7E7EBEBEBEBEBEBE3E3E3C7C7C7BCBCBCC9C9C9DADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADAD0D0D0BCBCBC959595919191B4B4B4D9D9D9E9
        E9E9E9E9E9D4D4D4D2D2D2DADADADADADADBDBDBDADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADAA6A6A6919191BFBFBFE2E2E2E4E4E4DDDDDD
        DCDCDCDADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADAD9D9D9939393A5A5A5D7D7D7E2E2E2E7E7E7DBDBDBDADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DAC1C1C1969696CFCFCFE4E4E4E7E7E7DADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADAD5D5D5929292CE
        CECEE5E5E5E7E7E7DADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
        CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
        CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
        CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADA929292CDCDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADA929292CD
        CDCDE5E5E5E6E6E6DADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADA939393CECECEE8E8E8E8E8E8
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADAD9D9D99C9C9CD2D2D2EAEAEAECECECDBDBDBDADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DACFCFCFB1B1B1DCDCDCEBEBEBF0F0F0E3E3E3DADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADABFBFBFCDCDCDE6
        E6E6EBEBEBECECECEEEEEEE3E3E3DBDBDBDADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
        DADADADADADADADADADADADADADAD3D3D3C9C9C9E3E3E3EAEAEAEBEBEBEBEBEB
        EBEBEBEBEBEBE7E7E7E4E4E4E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E1E1E1
        DEDEDED4D4D4D6D6D6E4E4E4EAEAEAEBEBEBEBEBEBEBEBEBEBEBEBEAEAEAE7E7
        E7E4E4E4E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2
        E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E1E1E1E1E1E1E5E5E5E9E9
        E9EBEBEBEBEBEBEBEBEB}
      Color = clBtnFace
      Caption = #20851#38381
      TabOrder = 2
      OnClick = btnCloseClick
    end
  end
  object RzPanel2: TRzPanel
    Left = 38
    Top = 94
    Width = 260
    Height = 31
    BorderOuter = fsStatus
    BorderWidth = 1
    Color = clWhite
    FlatColor = 9145227
    TabOrder = 1
    object RzPanel3: TRzPanel
      Left = 2
      Top = 2
      Width = 103
      Height = 27
      Align = alLeft
      BorderOuter = fsFlat
      BorderSides = [sdRight, sdBottom]
      FlatColor = clGray
      TabOrder = 0
      object RzBackground1: TRzBackground
        Left = 0
        Top = 0
        Width = 102
        Height = 26
        Active = True
        Align = alClient
        FrameColor = 9145227
        GradientColorStart = clWhite
        GradientColorStop = 14277081
        ImageStyle = isStretch
        ShowGradient = True
        ShowImage = False
        ShowTexture = False
      end
      object RzLabel1: TRzLabel
        Left = 0
        Top = 0
        Width = 102
        Height = 26
        Align = alClient
        Alignment = taCenter
        Caption = #20998#31867#21517#31216
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Height = -15
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = True
        Layout = tlCenter
        ShadowColor = 16250871
        ShadowDepth = 1
        TextStyle = tsShadow
      end
    end
    object edtSORT_NAME: TcxTextEdit
      Left = 105
      Top = 4
      Width = 153
      Height = 23
      Properties.MaxLength = 15
      TabOrder = 1
      ImeName = #20013#25991'('#31616#20307') - '#25628#29399#20116#31508#36755#20837#27861
    end
  end
  object cdsSort: TZQuery
    FieldDefs = <>
    CachedUpdates = True
    Params = <>
    Left = 8
    Top = 128
  end
end
