inherited frmDownStockOrder: TfrmDownStockOrder
  Left = 163
  Top = 118
  Caption = #21367#28895#20837#24211
  ClientHeight = 570
  ClientWidth = 1015
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 15
  inherited ScrollBox: TScrollBox
    Width = 1015
    Height = 570
    inherited webForm: TRzPanel
      Width = 1015
      Height = 570
      inherited bkgImage: TImage
        Width = 1015
        Height = 570
      end
      object RzPanel1: TRzPanel
        Left = 201
        Top = 96
        Width = 634
        Height = 361
        BorderOuter = fsFlatRounded
        TabOrder = 0
        object RzPanel2: TRzPanel
          Left = 2
          Top = 2
          Width = 630
          Height = 41
          Align = alTop
          BorderOuter = fsFlat
          BorderSides = [sdBottom]
          Color = 15461355
          TabOrder = 0
          object RzLabel1: TRzLabel
            Left = 15
            Top = 13
            Width = 114
            Height = 15
            Caption = #24403#21069#26377'   '#24352#35746#21333
          end
          object RzLabel2: TRzLabel
            Left = 63
            Top = 12
            Width = 20
            Height = 15
            Alignment = taCenter
            AutoSize = False
            Caption = '1'
            Font.Charset = GB2312_CHARSET
            Font.Color = clRed
            Font.Height = -15
            Font.Name = #23435#20307
            Font.Style = [fsBold]
            ParentFont = False
          end
        end
        object RzPanel3: TRzPanel
          Left = 2
          Top = 318
          Width = 630
          Height = 41
          Align = alBottom
          BorderOuter = fsFlat
          BorderSides = [sdTop]
          Color = 15461355
          TabOrder = 1
          object btnOK: TRzBmpButton
            Left = 507
            Top = 7
            Width = 106
            Height = 29
            Bitmaps.TransparentColor = clFuchsia
            Bitmaps.Up.Data = {
              76240000424D762400000000000036000000280000006A0000001D0000000100
              1800000000004024000000000000000000000000000000000000EBEBEBEAEAEA
              E5E5E5D9D9D9D0D0D0CECECECDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
              CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
              CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
              CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
              CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
              CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
              CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
              CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
              CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD
              CDCDCDCDCDCDCECECED0D0D0D9D9D9E5E5E5EAEAEAEBEBEB0000E9E9E9E0E0E0
              C7C7C7AAAAAA9999999393939292929292929292929292929292929292929292
              9292929292929292929292929292929292929292929292929292929292929292
              9292929292929292929292929292929292929292929292929292929292929292
              9292929292929292929292929292929292929292929292929292929292929292
              9292929292929292929292929292929292929292929292929292929292929292
              9292929292929292929292929292929292929292929292929292929292929292
              9292929292929292929292929292929292929292929292929292929292929292
              9292929292929292929292929292929292929292929292929292929292929292
              9292929292929292929292929292929292929292929292929292929292929292
              929292929292939393999999AAAAAAC7C7C7E0E0E0E9E9E90000E4E4E4C7C7C7
              C6C6C6D2D2D2DADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADAD0D0D0B9B9B98A8A8A9C9C9CC5C5C5E4E4E40000DADADAD8D8D8
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADAD3D3D38E8E8EA9A9A9D9D9D90000E1E1E1DFDFDF
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADABBBBBB979797D0D0D00000EAEAEADBDBDB
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADAD5D5D5929292CECECE0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CDCDCD0000EEEEEEDADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA929292CECECE0000EEEEEEDBDBDB
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADA979797D0D0D00000EFEFEFDFDFDF
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADAD6D6D6A9A9A9D9D9D90000EDEDEDE9E9E9
              DBDBDBDADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADAC6C6C6C5C5C5E4E4E40000EBEBEBEFEFEF
              E8E8E8E0E0E0DCDCDCDADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA
              DADADADADADADADADADADADAD7D7D7CACACAE0E0E0E9E9E90000EBEBEBEBEBEB
              EAEAEAE6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
              E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
              E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
              E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
              E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
              E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
              E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
              E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
              E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6E6
              E6E6E6E5E5E5E1E1E1DADADAD9D9D9E5E5E5EAEAEAEBEBEB0000}
            Color = clBtnFace
            Caption = #21367#28895#20837#24211
            TabOrder = 0
            OnClick = btnOKClick
          end
        end
        object RzPanel4: TRzPanel
          Left = 2
          Top = 43
          Width = 630
          Height = 275
          Align = alClient
          BorderOuter = fsStatus
          TabOrder = 2
          object DBGridEh1: TDBGridEh
            Left = 1
            Top = 1
            Width = 628
            Height = 273
            Align = alClient
            AllowedOperations = [alopUpdateEh]
            AutoFitColWidths = True
            BorderStyle = bsNone
            DataSource = OrderDataSource
            Flat = True
            FooterColor = clWindow
            FooterFont.Charset = GB2312_CHARSET
            FooterFont.Color = clBlack
            FooterFont.Height = -15
            FooterFont.Name = #23435#20307
            FooterFont.Style = []
            FrozenCols = 2
            ImeName = #20013#25991'('#31616#20307') - '#25628#29399#20116#31508#36755#20837#27861
            Options = [dgTitles, dgColumnResize, dgColLines, dgRowLines, dgTabs, dgAlwaysShowSelection, dgConfirmDelete, dgCancelOnExit]
            OptionsEh = [dghFixed3D, dghFrozen3D, dghHighlightFocus, dghClearSelection]
            PopupMenu = PopupMenu1
            RowHeight = 20
            TabOrder = 0
            TitleFont.Charset = GB2312_CHARSET
            TitleFont.Color = clBlack
            TitleFont.Height = -15
            TitleFont.Name = #23435#20307
            TitleFont.Style = []
            TitleHeight = 20
            UseMultiTitle = True
            IsDrawNullRow = False
            CurrencySymbol = #65509
            DecimalNumber = 2
            DigitalNumber = 12
            OnDrawColumnCell = DBGridEh1DrawColumnCell
            OnTitleClick = DBGridEh1TitleClick
            Columns = <
              item
                Checkboxes = True
                Color = clBtnFace
                EditButtons = <>
                FieldName = 'SELFLAG'
                Footers = <>
                KeyList.Strings = (
                  '1'
                  '0')
                PickList.Strings = (
                  '0'
                  '1')
                Tag = -1
                Title.Caption = #36873#25321
                Width = 35
              end
              item
                Color = clBtnFace
                EditButtons = <>
                FieldName = 'SEQNO'
                Footers = <>
                ReadOnly = True
                Title.Caption = #24207#21495
                Width = 35
              end
              item
                EditButtons = <>
                FieldName = 'ARR_DATE'
                Footers = <>
                ReadOnly = True
                Title.Caption = #36865#36798#26085#26399
                Width = 80
              end
              item
                EditButtons = <>
                FieldName = 'INDE_DATE'
                Footers = <>
                ReadOnly = True
                Title.Caption = #35746#36135#26085#26399
                Width = 80
              end
              item
                EditButtons = <>
                FieldName = 'CLIENT_NAME'
                Footers = <>
                ReadOnly = True
                Title.Caption = #20379#24212#21830
                Width = 180
              end
              item
                EditButtons = <>
                FieldName = 'INDE_AMT'
                Footers = <>
                ReadOnly = True
                Title.Caption = #35746#36135#25968#37327
                Width = 70
              end
              item
                EditButtons = <>
                FieldName = 'INDE_MNY'
                Footers = <>
                ReadOnly = True
                Title.Caption = #35746#36135#37329#39069
                Width = 70
              end
              item
                EditButtons = <>
                FieldName = 'NEED_AMT'
                Footers = <>
                ReadOnly = True
                Title.Caption = #38656#27714#25968#37327
                Width = 70
              end>
          end
        end
      end
    end
  end
  object cdsTable: TZQuery
    FieldDefs = <>
    CachedUpdates = True
    Params = <>
    Left = 258
    Top = 422
  end
  object OrderDataSource: TDataSource
    DataSet = cdsTable
    Left = 323
    Top = 424
  end
  object PopupMenu1: TPopupMenu
    AutoHotkeys = maManual
    Left = 417
    Top = 258
    object N1: TMenuItem
      AutoHotkeys = maManual
      Caption = #20840#36873
      ImageIndex = 46
      ShortCut = 16449
      OnClick = N1Click
    end
    object N2: TMenuItem
      AutoHotkeys = maManual
      Caption = #20840#21453#36873
      ShortCut = 16450
      OnClick = N2Click
    end
    object N3: TMenuItem
      AutoHotkeys = maManual
      Caption = #20840#19981#36873
      ShortCut = 16452
      OnClick = N3Click
    end
  end
end
