--销售订单状态
 insert into PUB_PARAMS(CODE_ID,CODE_NAME,TYPE_CODE,COMM,TIME_STAMP) values('0','待发货','SALBILL_STATUS','00',5497000);
 insert into PUB_PARAMS(CODE_ID,CODE_NAME,TYPE_CODE,COMM,TIME_STAMP) values('1','发货中','SALBILL_STATUS','00',5497000);
 insert into PUB_PARAMS(CODE_ID,CODE_NAME,TYPE_CODE,COMM,TIME_STAMP) values('2','已结案','SALBILL_STATUS','00',5497000);
--进货订单状态
 insert into PUB_PARAMS(CODE_ID,CODE_NAME,TYPE_CODE,COMM,TIME_STAMP) values('0','待入库','STKBILL_STATUS','00',5497000);
 insert into PUB_PARAMS(CODE_ID,CODE_NAME,TYPE_CODE,COMM,TIME_STAMP) values('1','入库中','STKBILL_STATUS','00',5497000);
 insert into PUB_PARAMS(CODE_ID,CODE_NAME,TYPE_CODE,COMM,TIME_STAMP) values('2','已结案','STKBILL_STATUS','00',5497000);

alter table SAL_INDENTORDER add SALBILL_STATUS int;
alter table STK_INDENTORDER add STKBILL_STATUS int;

update SAL_INDENTORDER set SALBILL_STATUS=0;

update SAL_INDENTORDER set SALBILL_STATUS=2 where Exists(select * from SAL_SALESORDER where TENANT_ID=SAL_INDENTORDER.TENANT_ID and FROM_ID=SAL_INDENTORDER.INDE_ID);

update STK_INDENTORDER set STKBILL_STATUS=0;

update STK_INDENTORDER set STKBILL_STATUS=2 where Exists(select * from STK_STOCKORDER where TENANT_ID=STK_INDENTORDER.TENANT_ID and FROM_ID=STK_INDENTORDER.INDE_ID);

insert into PUB_CODE_INFO(TENANT_ID,CODE_TYPE,COMM,TIME_STAMP,SEQ_NO,CODE_ID,CODE_NAME,CODE_SPELL) values(0,'8','00',5497000,210000,'210000','辽宁省','LNS'); 

delete from CA_MODULE where PROD_ID='E3_620' and MODU_ID in ('41300001','41300002','41300003','41300004');

