object frmWebForm: TfrmWebForm
  Left = 131
  Top = 80
  HorzScrollBar.Style = ssFlat
  HorzScrollBar.Tracking = True
  VertScrollBar.Style = ssFlat
  VertScrollBar.Tracking = True
  BorderIcons = []
  BorderStyle = bsNone
  ClientHeight = 462
  ClientWidth = 846
  Color = clWhite
  TransparentColorValue = clFuchsia
  Ctl3D = False
  Font.Charset = GB2312_CHARSET
  Font.Color = clBlack
  Font.Height = -15
  Font.Name = #23435#20307
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poMainFormCenter
  OnClose = FormClose
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 15
  object ScrollBox: TScrollBox
    Left = 0
    Top = 0
    Width = 846
    Height = 462
    Align = alClient
    BevelInner = bvNone
    BevelOuter = bvNone
    BorderStyle = bsNone
    TabOrder = 0
    object webForm: TRzPanel
      Left = 62
      Top = 48
      Width = 731
      Height = 308
      BorderOuter = fsNone
      Color = 16645629
      TabOrder = 0
    end
  end
end
