object frmHintMsg: TfrmHintMsg
  Left = 527
  Top = 243
  BorderStyle = bsToolWindow
  ClientHeight = 181
  ClientWidth = 267
  Color = clBtnFace
  Font.Charset = GB2312_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = #23435#20307
  Font.Style = [fsBold]
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 12
  object RzPanel1: TRzPanel
    Left = 0
    Top = 0
    Width = 267
    Height = 181
    Align = alClient
    BorderOuter = fsFlatRounded
    BorderColor = 16440232
    BorderShadow = 16440232
    Color = clWhite
    FlatColor = 8404992
    TabOrder = 0
    object RzPanel2: TRzPanel
      Left = 2
      Top = 147
      Width = 263
      Height = 32
      Align = alBottom
      BorderOuter = fsNone
      Color = clWhite
      TabOrder = 0
    end
    object RzPanel3: TRzPanel
      Left = 2
      Top = 33
      Width = 263
      Height = 114
      Align = alClient
      BorderOuter = fsNone
      Color = clWhite
      TabOrder = 1
    end
    object RzPanel4: TRzPanel
      Left = 2
      Top = 2
      Width = 263
      Height = 31
      Align = alTop
      BorderOuter = fsNone
      TabOrder = 2
      object RzBackground1: TRzBackground
        Left = 0
        Top = 0
        Width = 263
        Height = 31
        Active = True
        Align = alClient
        GradientColorStart = 16440232
        GradientColorStop = clWhite
        ImageStyle = isCenter
        ShowGradient = True
        ShowImage = False
        ShowTexture = False
      end
    end
  end
end
